[paper_sizes]
A5 = [148, 210]
A4 = [210, 297]
A3 = [297, 420]
A2 = [420, 594]
C64 = [4096, 4096]

[page]
bleed = [5,5]           # % bleed on x and y
pixels_per_mm = 10      # pixels per mm
landscape = true       # landscape or portrait

[colours]
stroke = 'black'
fill = 'none'
background = 'none'

[stroke]
width = 1

[directories]
output = '../output/'
optimised = 'optimised/'

[lint]
rcfile = '../pylintrc'
threshold = 9.9

[DEFAULT]
TITLE = 'DEFAULT PARAMETERS'
SIZE = [297, 420]    # A3
LANDSCAPE = true
PPMM = 10
BLEED = [5,5]
OUTPUT_DIR = '../output/'
OPTIMISED_DIR = '../output/optimised/'
STYLES = ['black', '10', 'none', 'none']
    [DEFAULT.LINE_STYLE]
    stroke = '#000'
    stroke-width = 10
    stroke-linecap = 'round'




[UTILS]
CM_PER_INCH = 2.54
